### PR TITLE
Start on fee breakdown on Order Information page [WIP]

### PR DESCRIPTION
**Pull request by 4855062503**
This is in reference to the second to last bulletin under 'Most Notable' in https://github.com/zap-me/ops/issues/202.

### CODE REVIEW

**Comment by zap-janitor** [comment]
🚀 Deployed on https://6322ae9fdd68dd5062297e8a--bitforge-test.netlify.app

**Comment by djpnewton** [comment]
we should also have the extra fee information in the "Order Information" page

**Comment by djpnewton** [comment]
can simplify this by leveraging https://github.com/zap-me/beryllium/pull/118

**Comment by djpnewton** [comment]
close in favor of https://github.com/zap-me/alloy/pull/92

**Pull request closed without merging**
