### PR TITLE
Add arrow pagination to Orders page

### PR DESCRIPTION
**Pull request by 4855062503**

### CODE REVIEW

**Comment by djpnewton** [comment]
- We need to be able to see how many pages in total there are and to be able to skip ahead (see https://www.timble.net/blog/2015/05/better-pagination-for-jekyll/)


- If I click previous fast I get an error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Index out of range: index must not be negative: -7
```

- You need to move the orders request function into the orders screen so you can do a new request when clicking the pagination buttons

- the second page shows 9 orders instead of 7?

**Comment by djpnewton** [comment]
what is the status of this PR?

**Comment by 4855062503** [comment]
> what is the status of this PR?

Updated PR.

**Comment by djpnewton** [comment]
what is the status of this PR?

**Comment by 4855062503** [comment]
> what is the status of this PR?

new PR: https://github.com/zap-me/alloy/pull/8

**Pull request closed without merging**
