### PR TITLE
Server specific settings

### PR DESCRIPTION
**Pull request by djpnewton**
add server specific settings so that we dont have to re-login when changing from localhost to beryllium-test etc

also add web background image into the app and fix the background image size on the web page (fix viewport scalling etc)

### CODE REVIEW

**Comment by djpnewton** [comment]
check out this:
image
image
image
image

**Review by 4855062503 — COMMENTED** [review]
Nice. That looks good.

Do you think the unused space around the `ColumnView` should show the `BackgroundWebImage` too?

**Review by eoliveros — APPROVED** [review]

**Comment by djpnewton** [comment]
> @djpnewton
> 
> Nice. That looks good.
> 
> Do you think the unused space around the `ColumnView` should show the `BackgroundWebImage` too?
> 
> e.g. https://gyazo.com/89dacac24b89fffdaf685cb99c951cf3

I thought about applying it to the other pages also. I am think the Columnview will not be able to do it because it is not the full width of the screen

**Comment by djpnewton** [comment]
apply background to all pages (looks cool actually) and got an order page that forgot to add the ColumnView before

**Pull request merged**
