### PR TITLE
Place market value checkboxes in a Column widget instead of Row

### PR DESCRIPTION
**Pull request by 4855062503**
This is in reference to the last bullet point under 'Buggy' in https://github.com/zap-me/ops/issues/191 .

### CODE REVIEW

**Comment by zap-janitor** [comment]
🚀 Deployed on https://630d19f59f0bdf206ee85e60--bitforge-test.netlify.app

**Review by djpnewton — CHANGES_REQUESTED** [review]
I think we need a bigger vertical spacer inbetween the sections.

And make the 'Estimated Market Value' and 'Currency Units' text bigger to show they are headers

**Review by djpnewton — CHANGES_REQUESTED** [review]
ok cool 

I reckon make the title text a bit bigger (fontsize 16?) and squash the commits

**Comment by djpnewton** [comment]
Cant really tell that the fontSize 16 is doing anything?

image

**Comment by 4855062503** [comment]
@djpnewton 
17 looks the best.

**Review by djpnewton — APPROVED** [review]

**Pull request merged**
