### PR TITLE
implement autobuy UI

### PR DESCRIPTION
**Pull request by djpnewton**
TODO:
 - make the UI nicer

needs https://github.com/zap-me/beryllium/pull/89 on the server

### CODE REVIEW

**Comment by zap-janitor** [comment]
🚀 Deployed on https://630d9e60f8bb53764a6f9676--bitforge-test.netlify.app

**Review by 4855062503 — APPROVED** [review]
LGTM. Would be good to add a Continue button consistent with other buttons later and centre text / info.

**Comment by djpnewton** [comment]
updated code for review

**Review by 4855062503 — APPROVED** [review]
LGTM.

**Pull request merged**
