### PR TITLE
New pagination PR

### PR DESCRIPTION
**Pull request by 4855062503**
Made a new pagination PR as it was easier than redoing code for the requests stuff.

### CODE REVIEW

**Comment by 4855062503** [comment]
Just adding a loading spinner when clicking another page, in the event it takes a while to load.

**Comment by djpnewton** [comment]
It does not look like basic testing has been done.

There should not be a next arrow with just two items:
Screen Shot 2021-09-21 at 9 55 12 PM


After I click next:
Screen Shot 2021-09-21 at 9 55 25 PM


After I click back:
Screen Shot 2021-09-21 at 9 55 35 PM

**Comment by 4855062503** [comment]
@djpnewton Should be fixed now

**Comment by djpnewton** [comment]
You need to test more thoroughly before giving it to me. You need to think through the various states that a user will encounter and how to handle them. 

1) Why are the orders being loaded before entering the order screen when they are not being used because after the order screen shows the order are loaded again

2) Why is there are next button if I only have two orders?:
Screen Shot 2021-09-21 at 11 21 52 PM

3) Why do I get an empty screen when I click next?:
Screen Shot 2021-09-21 at 11 22 01 PM

**Comment by 4855062503** [comment]
Have updated:

- Add 'querying' spinner each time a request is made for getting orders
- Remove redundant initial request performed in `lib/main.dart`
- Remove forward arrow if next page is empty
- Added padding to arrows
- Remove boilerplate code which could be shrunk into a few lines
- Space out arrows a bit better

Tested on web, haven't tested on a mobile device yet.

**Pull request closed without merging**
