### PR TITLE
submit forms when pressing enter

### PR DESCRIPTION
**Pull request by djpnewton**

### CODE REVIEW

**Comment by zap-janitor** [comment]
🚀 Deployed on https://630edb3521e8543dc0ff8b53--bitforge-test.netlify.app

**Comment by 4855062503** [comment]
Nice. Would be good if this worked for the Exchange widget / Create Order function too.

**Review by 4855062503 — APPROVED** [review]
LGTM.

**Comment by djpnewton** [comment]
> Nice. Would be good if this worked for the Exchange widget / Create Order function too.

added

**Pull request merged**
