### PR TITLE
Add human readable dates to ListTiles containing financial history

### PR DESCRIPTION
**Pull request by 4855062503**
Will continue to update this PR.

This is based off of `order/deposit/withdrawal history to show dates in list view #C - Alex` [in this issue](https://github.com/zap-me/ops/issues/180)

### CODE REVIEW

**Comment by djpnewton** [comment]
The date should have the year like this

**Comment by djpnewton** [comment]
Also need to add it for the orders history

**Comment by 4855062503** [comment]
@djpnewton 

- [This](https://gyazo.com/90177a33e2364f5760f1731a3a21cb86) is what the orders page looks like
- [This](https://gyazo.com/c4900292b51e85416bf2f1203759c470) is what the deposits/withdrawals page looks like

Do you want the dates to be more in the corner on the left like the Zap app or is the current format fine?

**Comment by djpnewton** [comment]
I think if we are going to redo these list items lets do it properly and make it real nice like the image from the zap app.

Here is the code: https://github.com/zap-me/zapm_app/blob/2b17003cbb32dec7c4b9c0792ee0ba9b7ab419f0/lib/transactions.dart#L67

We can make a dark version for bitforge

**Comment by 4855062503** [comment]
Think I accidentally pulled in latest changes to master. May need to rebase later.

**Pull request closed without merging**
