### PR TITLE
Start on exchange rate widget

### PR DESCRIPTION
**Pull request by 4855062503**
This is in reference to the design recommendation in https://github.com/zap-me/ops/issues/191.

### CODE REVIEW

**Comment by zap-janitor** [comment]
🚀 Deployed on https://630ebac340bedd2a58cf74a4--bitforge-test.netlify.app

**Comment by 4855062503** [comment]
I have noticed than on an initial load, the exchange rate shows as "...".

Will look into fixing this.

**Comment by 4855062503** [comment]
@djpnewton 

Not sure if I should wrap this usage of PriceEquivalent in its own class.

Ok if you take a look?

**Comment by djpnewton** [comment]
> @djpnewton
> 
> Not sure if I should wrap this usage of PriceEquivalent in to its own class.
> 
> Ok if you take a look?

Yeah I think you want to make a common abstract parent class that implements `_formattedPrice()`

**Comment by 4855062503** [comment]
I'm thinking that maybe I should make it so `_formattedPrice()` returns the price in accounting format, e.g. `32,000` instead of `32000` to improve readability.

**Review by djpnewton — APPROVED** [review]

**Pull request merged**
