### PR TITLE
Show asset equivalent value in NZD

### PR DESCRIPTION
**Pull request by djpnewton**
-revamp unit selection
-add 'show asset value' option to allow showing an equivalent value in another asset

### CODE REVIEW

**Review by eoliveros — APPROVED** [review]

**Comment by eoliveros** [comment]
> @eoliveros how can you approve this change if it didnt pass the checks?

I looked at the code and it looked fine to me

**Comment by 4855062503** [comment]
@djpnewton :
From a UX POV what would be the benefit of showing asset values in cents?
Also why have 'Asset prices' and 'Asset units'? Even if I select asset price as NZD, my withdrawals are still denominated in sats/BTC, same with user balance.
I like the 2x2 grid, but feel it could be centered.
The 'Amount' info of the withdrawals now show like this: 100 sat (...).
E.g. https://gyazo.com/eb3bcd06d7998c08e11a3842cfecfa8b
Is the asset price supposed to be between the parentheses?
Ran + read code. LGTM.

**Comment by djpnewton** [comment]
> > @eoliveros how can you approve this change if it didnt pass the checks?
> 
> I looked at the code and it looked fine to me

when we review each others PR we its about the project as a whole. If one PR gets committed which breaks tests/CI etc then it causes problems for others

> @djpnewton : From a UX POV what would be the benefit of showing asset values in cents?

No real point, I just put that in so I could test some extra scenarios

> Also why have 'Asset prices' and 'Asset units'? Even if I select asset price as NZD, my withdrawals are still denominated in sats/BTC, same with user balance.

Yes your withdrawal is denominated in the `asset unit` you select but then we also show an equivalent `asset price` in brackets.. If you can think of a better way to name it let me know

> I like the 2x2 grid, but feel it could be centered.

sure ok

> The 'Amount' info of the withdrawals now show like this: 100 sat (...). E.g. https://gyazo.com/eb3bcd06d7998c08e11a3842cfecfa8b Is the asset price supposed to be between the parentheses? Ran + read code. LGTM.

What settings in the units page did you have?

**Comment by 4855062503** [comment]
>No real point, I just put that in so I could test some extra scenarios

Ok cool. Guess it could be cool for smaller orders etc

>What settings in the units page did you have?
cents for Asset Price
sats for BTC Asset Unit
cents for NZD Asset Unit

**Comment by djpnewton** [comment]
I cant seem to reproduce the issue. It might just have been a one off network request that failed?

The main other issue is I think   the wording on this page could be better.. any ideas?:

- and "Asset Prices" -> "Estimated Market Value"?
- maybe "Asset Units" -> "Currency Units"?

image

**Comment by 4855062503** [comment]
>and "Asset Prices" -> "Estimated Market Value"?
>maybe "Asset Units" -> "Currency Units"?

These both sound good.

>I cant seem to reproduce the issue. It might just have been a one off network request that failed?

I'm getting [it](https://gyazo.com/269d21c66060c5970cd479f305d5e22d) again, only network requests which failed said `old nonce`

**Comment by 4855062503** [comment]
Was because I was on testnet.

Using `be.bitforge,me` now, cents market value, looks real nice.

https://gyazo.com/a48ede988a87395e7a1614e1d6450516

**Comment by djpnewton** [comment]
ok, I think I have everything covered, also show the price equivalent for the balances

**Comment by djpnewton** [comment]
@eoliveros  @4855062503  review plz

**Comment by eoliveros** [comment]
set the unit to cents and then i created a deposit  of 10 cents:
image

so that looks good. also shows the balances in cents:
image

when changed to NZD:
image


looks good to me.

**Review by eoliveros — APPROVED** [review]
changing the units from NZD to cents and viewing the balances is showing as cents and when changed back to NZD the balances goes back to NZD. So it appears to be working.

**Pull request merged**
